### ISSUE TITLE
add filter to endpoint_calls

### ISSUE THREAD

**Issue by Areso** [Areso/Oblache#41]
```
     id_call: 5
    endpoint: db_create
      ipaddr: 
      uagent: curl/7.81.0
     headers: {'Host': 'dbend.areso.pro', 'X-Real-Ip': '212.31.102.114', 'X-Forwarded-For': '212.31.102.114', 'X-Forwarded-Proto': 'https', 'Connection': 'close', 'Content-Length': '49', 'User-Agent': 'curl/7.81.0', 'Accept': '*/*', 'Cookie': 'sid=d05ed417-6897-4c15-8af9-714bf2727397', 'Content-Type': 'application/x-www-form-urlencoded'}
accept_langs: 
uagent_langs: None
        user: None
      dt_utc: 2024-02-02 00:49:35
5 rows in set (0.00 sec)
```
at least, add user.

**Comment by Areso** [comment]
Nope, this one is not yet implemented

**Comment by Areso** [comment]
Fill `user` field in the decorator

**Comment by Areso** [comment]
also, I don't like here empty ipaddr field. Could be a problem on public installation.

**Comment by Areso** [comment]
```
mysql> select * from endpoint_calls\G
*************************** 1. row ***************************
     id_call: 1
    endpoint: tos
      ipaddr: 
      uagent: curl/7.81.0
     headers: {'Host': 'dbend.areso.pro', 'X-Real-Ip': '212.31.102.114', 'X-Forwarded-For': '212.31.102.114', 'X-Forwarded-Proto': 'https', 'Connection': 'close', 'User-Agent': 'curl/7.81.0', 'Accept': '*/*'}
accept_langs: 
uagent_langs: None
      id_acc: NULL
      dt_utc: 2024-02-03 22:05:13
*************************** 2. row ***************************
     id_call: 2
    endpoint: db_list
      ipaddr: 
      uagent: curl/7.81.0
     headers: {'Host': 'dbend.areso.pro', 'X-Real-Ip': '212.31.102.114', 'X-Forwarded-For': '212.31.102.114', 'X-Forwarded-Proto': 'https', 'Connection': 'close', 'User-Agent': 'curl/7.81.0', 'Accept': '*/*', 'Cookie': 'sid=35726d42-27cf-4047-92cf-b36df8ea42b8', 'Content-Type': 'application/json'}
accept_langs: 
uagent_langs: None
      id_acc: 1
      dt_utc: 2024-02-03 22:06:13
2 rows in set (0.00 sec)
```
