### ISSUE TITLE
[Bug] After deletion the database still has size in dbs table

### ISSUE THREAD

**Issue by Areso** [Areso/Oblache#9]

**Comment by Areso** [comment]
To check:
1) create MySQL database 
2) create table inside it
3) add 10k records (bash / python / whatever script)
4) check size of the database in Oblache (Web UI)
5) write down it's size, write down the UUID of the database
6) delete database in Web UI
7) write here as a comment UUID, size of the database before deletion

**Comment by Areso** [comment]
```
mysql> select * from dbs where db_name="db_7lki1g42"\G
*************************** 1. row ***************************
            id_db: 1092
          db_uuid: 065fb320-3736-7135-8000-7702efc41593
           id_acc: 350
        id_dbtype: 3
       id_version: 5
        id_region: 3
          id_host: 2
       id_envtype: 3
           id_env: NULL
          db_name: db_7lki1g42
       admin_user: 
        admin_pwd: 
      auth_method: NULL
       order_body: {"db_uuid": "065fb320-3736-7135-8000-7702efc41593", "id_dbtype": 3, "id_version": 5, "id_envtype": 3, "db_name": "", "id_region": 3}
              dsn: mysql://user_:pw_@cisdb1.areso.pro:3306/db_7lki1g42
       order_date: 2024-03-20 18:59:15
      create_date: 2024-03-20 18:59:27
       error_date: NULL
delete_order_date: 2024-04-02 19:43:51
      delete_date: 2024-04-02 19:44:05
       db_size_mb: 0.000
       is_blocked: 0
       is_deleted: 0
        id_status: 4
   status_history: NULL
1 row in set (0.00 sec)

```
